apiVersion: v1
kind: Service
metadata:
  name: ethereum-geth
  namespace: eth
  labels:
    app: ethereum-geth
spec:
  #type: NodePort
  type: ClusterIP
  selector:
    app: ethereum-geth
  ports:
    - name: http
      port: 8545
      targetPort: 8545
      #nodePort: 30000
      protocol: TCP
    - name: engine
      port: 8551
      targetPort: 8551
      protocol: TCP

