apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: audio-scraper-ingress
  namespace: audio-scraper
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - audio-scraper.prayujt.com
    secretName: audio-scraper-prayujt-com-certs
  rules:
  - host: audio-scraper.prayujt.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: audio-scraper
            port:
              number: 8080
